version: '3.5'

services:
  nginx:
    image: 'nginx:1.18.0-alpine'
    depends_on: 
      - webapp
    volumes:
      - './nginx/conf.d/:/etc/nginx/conf.d/'
    ports:
      - '8080:80'
    networks:
      - app-network
  
  webapp:
    build:
      context: webapp
    networks:
      - app-network

  api:
    build:
      context: api
    networks:
      - app-network
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    
  auth:
    build:
      context: auth
    networks:
      - app-network

  postgis:
    build:
      context: postgis
    ports:
      - '5432:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge