version: "3.5"

services:
  webapp:
    # выполнить `docker-compose build webapp` при переходе в `dev режим` или изменении зависимостей
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./webapp:/dev-app
      - /dev-app/node_modules # exclude
      - /dev-app/.fable # exclude
      - /dev-app/src/bin # exclude
      - /dev-app/src/obj # exclude
  api:
    # выполнить `docker-compose build webapp` при переходе в `dev режим` или изменении зависимостей
    build: 
      dockerfile: Dockerfile.dev
    volumes: 
      - ./api:/app
      - /app/src/bin # exclude
      - /app/src/obj # exclude
      