###

GET https://localhost:5001/

###

GET https://localhost:5001/secured
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkE3MzZCQjUwRDA1MDlBMjY3MTgyMzkwRkZGODU1Mzg5IiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE1OTQ5MTg1MTIsImV4cCI6MTU5NDkyMjExMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo2MDAwIiwiY2xpZW50X2lkIjoiY2xpZW50X2lkIiwianRpIjoiREQyQjNCNDkzQTQyRDAwOUMwQkY4NEE1OTMwMkVCRDciLCJpYXQiOjE1OTQ5MTg1MTIsInNjb3BlIjpbImFwaSJdfQ.SsRnLvpCA5mQN7zlMD67eAVlre0UWAQY04OXQq7Oa76QCFbGWTsj5gmrtEErRAdZzvgaCk-X3390u8W0Hcu2Rg3kg_EzoODA6xejf6Pazg41u159yGZMJTu63LfXAtb5WekgdwJNscFO5ieRiD4prYbbP71WnL97vP1xb2ujPE7xWPoUC-H540yrcnXis3CZfUDemTlXuz4xR-ZcS3rhK7uwl9HLuz_YrUaLH00MKiCo7gISvZzcbra02d-ymtOaS9fYUuXp1AB8RW7NCitrW3y2IfmPbDd4RS9Jc0HEO2GdCO1rbVcTJS2tB8v8u1ZxWJzSlAm4zWbhFiCT8qYR-w